#!/bin/bash

####### Data Collection #######

CURRENTDATE=$(date)

#SYSTEM INFORMATION

MYHOSTNAME=$(hostname)

OPERATINGSYSTEM=$(hostnamectl | grep 'Operating System' | sed 's/.*: //')

UPTIME=$(uptime -p)


#HARDWARE INFORMATION

CPU_MODEL=$(lscpu | grep -i "Model name" | sed 's/Model name:[[:blank:]]*//;s/@.*//') 

CPU_MAXSPEED=$(sudo dmidecode | grep -I "Max Speed:" | head -n 1 | sed 's/.*Max Speed: //')

CPU_CURRENTSPEED=$(sudo dmidecode | grep -I "Current Speed:" | head -n 1 | sed 's/.*Current Speed: //')

RAM=$(free -h | awk 'FNR==2 {print $2}')

DISKINFO=$(sudo parted -l | grep -Ew 'Model|Disk /*') #Make, Model, and size for all installed disks

VIDEOCARD=$(sudo lspci | grep 'VGA' | sed 's/.*: //') #Make and Model of video card


#NETWORK INFORMATION

FQDN=$(hostname --all-fqdns)

HOSTIP=$(hostname -i) #IP address for hostname

GATEWAYIP=$(ip route | grep 'default' | sed 's/.*via.//;s/.dev.*//')

DNSSERVER_IP=$(cat /etc/resolv.conf | grep 'nameserver' | sed 's/nameserver.//') #IP of DNS server

NETWORKCARD=$(sudo lspci | grep -im 1 'Ethernet' | sed 's/.*:.//') #Make and model of network card

IPADDRESSES=$(ip a | grep -w "global" | awk '{print $2}' | sed -z 's/\n/, /') #IP addresses in CIDR format


#SYSTEM STATUS

USERSLOGGEDIN=$(who | awk '{print $1}' | sed -z 's/\n/, /g')

DISKSPACE=$(df -h | awk 'FNR>1 { print $6, $4 }') #Free space for local filesystems in format: /mountpoint N

PROCESSCOUNT=$(ps -e --no-headers | wc -l)

LOADAVG=$(cat /proc/loadavg | awk '{print $1, $2, $3}' | sed 's/ /, /g')

LISTENINGPORTS=$(sudo ss -lntu | grep -i 'listen' | awk '{print $5}' | sed 's/^.*://' | sed -z 's/\n/, /g')

UFWDATA=$(sudo ufw status)

#MEMORYALLOCATION

TOTAL_MEMORY=$(free -h | awk 'FNR==2 {print $2}')
USED_MEMORY=$(free -h | awk 'FNR==2 {print $3}')
AVAIL_MEMORY=$(free -h | awk 'FNR==2 {print $7}')
FREE_MEMORY=$(free -h | awk 'FNR==2 {print $4}')

####### Report Template #######

cat<<EOF

System Report generated by $USER on $CURRENTDATE
 
System Information
------------------
Hostname: $MYHOSTNAME
OS: $OPERATINGSYSTEM
Uptime: $UPTIME
 
Hardware Information
--------------------
CPU Model: $CPU_MODEL
CPU Speed: Maximum = $CPU_MAXSPEED, Current = $CPU_CURRENTSPEED 
Total RAM Size: $RAM
Disk Information: $DISKINFO
Video Card Model: $VIDEOCARD
 
Network Information
-------------------
FQDN: $FQDN
Host Address: $HOSTIP
Gateway IP: $GATEWAYIP
DNS Server: $DNSSERVER_IP
 
InterfaceName: $NETWORKCARD
IP Address: $IPADDRESSES
 
System Status
-------------
Users Logged In: $USERSLOGGEDIN
Disk Space:
Mountpoint Size
$DISKSPACE
Process Count: $PROCESSCOUNT
Load Averages: $LOADAVG
Memory Allocation:
   Total Memory = $TOTAL_MEMORY
   Used Memory = $USED_MEMORY
   Unused Memory = $FREE_MEMORY
   Available Memory = $AVAIL_MEMORY
Listening Network Ports: $LISTENINGPORTS
Firewall (UFW) Info:
  $UFWDATA

EOF

