#!/bin/bash

####### Data Collection #######

#Get current date
currentdate=$(date)

### SYSTEM INFORMATION ###

#Get hostname
myhostname=$(hostname)

#Get OS information and remove text before OS distro and version
operatingsystem=$(hostnamectl | grep 'Operating System' | sed 's/.*: //') 

#Get uptime
uptime=$(uptime -p)

### HARDWARE INFORMATION ###

#Get only processor make/vendor and model/product
cpu_model=$(sudo lshw -C CPU | grep -Em 2 'vendor|product') 

#Get maximum CPU speed and format output to only contain actual value and no labels
cpu_maxspeed=$(sudo dmidecode | grep -I "Max Speed:" | head -n 1 | sed 's/.*Max Speed: //')

#Get current CPU speed and format output to only contain actual value and no labels
cpu_currentspeed=$(sudo dmidecode | grep -I "Current Speed:" | head -n 1 | sed 's/.*Current Speed: //')

#Get total ram size only, used awk to select for specific value from output
ramsize=$(free -h | awk 'FNR==2 {print $2}')

#Get make, model, size of installed disks; added spaces before each line in the output for formatting of final system report
diskinfo=$(sudo parted -l | grep -Eiw 'Model|Disk /*'| sed 's/^/       /')

#Get videocard make and model
videocard=$(sudo lshw -C video | grep -E 'vendor|product')

### NETWORK INFORMATION ###

#Get all FQDNS for the host
fqdn=$(hostname --all-fqdns)

#Get IP address associated with hostname
host_ip=$(hostname -i) #IP address for hostname

#Get default route and format to remove text before and after the IP address (only return IP address in output)
gateway_ip=$(ip route | grep 'default' | sed 's/.*via.//;s/.dev.*//')

#Get nameserver IP address and remove text before IP address in output (only return IP address in output)
dnsserver_ip=$(cat /etc/resolv.conf | grep 'nameserver' | sed 's/nameserver.//') 

#Get make and model of network card, include name of interface
networkcard=$(sudo lshw -C network | grep -Ei 'vendor|product|logical name')

#Get IP address in CIDR format, label each address with it's corresponding interface, format the output to one line and separate with commas
ipaddresses=$(ip a | grep -w "global" | awk '{print $9" = "$2}' | sed -z 's/\n/, /g;s/, $//')

### SYSTEM STATUS ###

#Get logged in users and format output to contain only usernames, separated by commas in a single line
usersloggedin=$(who | awk '{print $1}' | sed -z 's/\n/, /g;s/, $//')

#Get free space for local filesystems; added spaces before each line in the output for formatting of final system report
diskspace=$(df -lh | awk 'FNR>1 { print $6, $4 }'| sed 's/^/       /') 

#Count number of processes
processcount=$(ps -e --no-headers | wc -l)

#Get load averages and format output to be separated by commas
loadavg=$(cat /proc/loadavg | awk '{print $1, $2, $3}' | sed 's/ /, /g')

#Get listening network ports, format output to only have the port numbers and be separated by commas instead of new lines
listening_ports=$(sudo ss -lntu | grep -i 'listen' | awk '{print $5}' | sed 's/^.*://' | sed -z 's/\n/, /g;s/, $//')

#Get firewall status and UFW rules (if configured) and add spaces before each line in the output for formatting of final system report
ufwdata=$(sudo ufw status | sed 's/^/       /')

### MEMORY ALLOCATION ###

#Get memory (RAM) allocation information from free and make it human readable
total_memory=$(free -h | awk 'FNR==2 {print $2}')
used_memory=$(free -h | awk 'FNR==2 {print $3}')
avail_memory=$(free -h | awk 'FNR==2 {print $7}')
free_memory=$(free -h | awk 'FNR==2 {print $4}')

####### Report Template #######

cat<<EOF

System Report generated by $USER on $currentdate

System Information
------------------
Hostname: $myhostname
OS: $operatingsystem
Uptime: $uptime

Hardware Information
--------------------
CPU Model:
$cpu_model
CPU Speed: Maximum = $cpu_maxspeed, Current = $cpu_currentspeed 
Total RAM Size: $ramsize
Disk Information:
$diskinfo
VideoCard:
$videocard

Network Information
-------------------
FQDN: $fqdn
Host Address: $host_ip
Gateway IP: $gateway_ip
DNS Server: $dnsserver_ip

InterfaceName:
$networkcard
IP Address(es): $ipaddresses

System Status
-------------
Users Logged In: $usersloggedin
Disk Space:
       Mountpoint Size
$diskspace
Process Count: $processcount
Load Averages: $loadavg
Memory Allocation:
       Total Memory = $total_memory
       Used Memory = $used_memory
       Unused Memory = $free_memory
       Available Memory = $avail_memory
Listening Network Ports: $listening_ports
Firewall (UFW) Rules:
$ufwdata
EOF
